services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch-node01
    environment:
      - node.name=node01
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - elasticsearch

networks:
  es-network:
    driver: bridge
