filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/kodi/*.log

setup.template: # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-template.html
  enabled: true
  name: "kodi"
  pattern: "kodi-*"
  overwrite: false

setup.kibana:
  host: "192.168.178.47:5601"

setup.ilm: # https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html
  enabled: false
  rollover_alias: "kodi"

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS:192.168.178.47:9200}"
  index: "kodi-%{+yyyy.MM.dd}" # https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_escape_html
